apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: lokeans.lokean.infra.watch
spec:
  group: lokean.infra.watch
  names:
    kind: Lokean
    listKind: LokeanList
    plural: lokeans
    singular: lokean
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
