---
galaxy_info:
  author: Red Hat CloudOps
  description: Lokean Operator
  company: Red Hat, Inc

  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  # issue_tracker_url: http://example.com/issue/tracker

  # Some suggested licenses:
  # - BSD (default)
  # - MIT
  # - GPLv2
  # - GPLv3
  # - Apache
  # - CC-BY
  license: Apache

  min_ansible_version: 2.9

  platforms:
  - name: RHEL
    versions:
    - 7
  - name: CentOS
    versions:
    - 7

  galaxy_tags:
    - monitoring
    - telemetry

dependencies: []
