---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lokean-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: lokean-operator
  template:
    metadata:
      labels:
        name: lokean-operator
    spec:
      serviceAccountName: lokean-operator
      containers:
        - name: ansible
          command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          image: PLACEHOLDER-OPERATOR-URL
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
            readOnly: true
        - name: lokean-operator
          image: PLACEHOLDER-OPERATOR-URL
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "lokean-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
            - name: LOKEAN_IMAGE
              value: PLACEHOLDER-LOKEAN-URL
            - name: BRIDGE_SMARTGATEWAY_IMAGE
              value: quay.io/infrawatch/sg-bridge:latest
      volumes:
        - name: runner
          emptyDir: {}
