---
# tasks file for lokean
# this will be useful later to understand if we're on vanilla k8s or OpenShift (OKD)
- name: "Get information about the cluster"
  set_fact:
    api_groups: "{{ lookup('k8s', cluster_info='api_groups') }}"

- name: "Set Lokean container image"
  set_fact:
    container_image_path: "{{ lookup('env', 'LOKEAN_IMAGE') | default('PLACEHOLDER-LOKEAN-URL', true) }}"
    bridge_image_path: "{{ lookup('env', 'BRIDGE_SMARTGATEWAY_IMAGE') | default('quay.io/infrawatch/sg-bridge:latest', true) }}"

- name: Get Lokean ConfigMap Environment
  set_fact:
    lokean_resource_configmap:
      env: "{{ lookup('template', item.name) | from_yaml }}"
  when: item.to_load | default(True)
  loop:
    - name: lokean-configmap.yaml.j2
      to_load: "{{ True }}"

- name: Deploy Lokean
  k8s:
    state: "{{ state }}"
    definition: "{{ lookup('template', item.name) | from_yaml }}"
  when: item.to_load | default(True)
  loop:
    - name: deployment.yaml.j2
      to_load: "{{ True }}"
    - name: lokean-configmap.yaml.j2
      to_load: "{{ True }}"
